language: python
python:
  - '3.7.9'

before_script:
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="eden_conception.settings.travis"

# safelist
branches:
  only:
    - staging

services:
  - postgresql

script:
  - ./manage.py test
