# Generated by Django 3.2.2 on 2021-06-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_timesheet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='unit_hour',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
    ]
