# Generated by Django 3.2.2 on 2021-05-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectlist_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
    ]
