# Generated by Django 3.2.2 on 2021-06-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_list_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['name']},
        ),
    ]
