# Generated by Django 3.2.2 on 2021-06-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AddField(
            model_name='task',
            name='index',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
