# Generated by Django 3.2.2 on 2021-05-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectlist_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectlist',
            old_name='project_id',
            new_name='project',
        ),
    ]
