# Generated by Django 3.2.2 on 2021-06-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210611_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='task',
            name='planned_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
