# Generated by Django 3.2.2 on 2021-05-28 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_project_id_projectlist_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='project_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project.projectlist'),
            preserve_default=False,
        ),
    ]
