# Generated by Django 3.2.2 on 2021-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_projecttask_project_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
