# Generated by Django 3.2.2 on 2021-05-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_projecttask_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
