# Generated by Django 3.2.2 on 2021-05-28 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210528_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 14, 21, 32, 346041, tzinfo=utc)),
        ),
    ]
