# Generated by Django 3.2.2 on 2021-05-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='number_task',
            field=models.IntegerField(default=0),
        ),
    ]
